Added Section3.1 Business context
Arquisoft/dede_en2a pull request #39
Opened 2022-02-17 15:52 UTC by uo277776

Hi @uo277915! I finished writing the business context section assigned in #15 . Any comment or suggestion to improve it, would be great.

I also send you here the image of the diagram, because you won't be able to see it unless you build the html file. You will only see the PlantUML code instead.

![bcontext](https://user-images.githubusercontent.com/90835490/154518269-c9346242-0474-40a6-9588-8c185bf6f32f.jpg)

2022-02-18 21:02 UTC, uo277915 requested changes
Hey, I have found some typos in the code but in general, I think you've done a really good job!

I especially like the diagram, it is very clear!

2022-02-18 21:05 UTC, uo277915 requested changes
I think I messed up and didn't add half the comments 🤡
Here are the rest of them!

--

Hey, I have found some typos in the code but in general, I think you've done a really good job!

I especially like the diagram, it is very clear!

2022-02-18 21:05 UTC, uo277915 commented on docs/03_system_scope_and_context.adoc
> +|The app will display information store in the database and show it to the user. Also it will receive the information from the user using the PODs.
I think the correct tense for 'store' is **stored**

2022-02-18 21:05 UTC, uo277915 commented on docs/03_system_scope_and_context.adoc
> +|The api will send queries to the database and convert the response received in order to send back the information in a proper way to the WebApp.
I think this should end with "for the WebApp" instead of using 'to'

2022-02-20 19:47 UTC, uo277776 commented
Hi, I made the changes you requested, take a look if anything more has to be change.

Sorry for not doing it sooner, I couldn't do anything all weekend.

2022-02-21 10:11 UTC, merged