User verification
Arquisoft/dede_en2a pull request #94
Opened 2022-03-06 12:03 UTC by uo271580

I've finished the user verification. Every user has to check the email and click a link to finish the registration.

Give it a look whenever you can

2022-03-07 11:00 UTC, angelip2303 requested changes

2022-03-08 11:58 UTC, uo271580 commented
It´s not much but it's honest work

2022-03-08 15:47 UTC, angelip2303 commented
Perfect, now everything seems fine!

2022-03-08 15:48 UTC, angelip2303 approved these changes

2022-03-09 13:44 UTC, uo277776 approved these changes
Now, it seems good! Nice work!

2022-03-09 13:45 UTC, merged